version: '3.7'

services:
  web:
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    container_name: omabs_design_local_web
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev

  db:
    container_name: omabs_design_local_db
    env_file:
      - ./.env.dev.db

#  redis:
#    container_name: currentic_local_redis
#
#  celery:
#    env_file:
#      - ./.env.dev

volumes:
  postgres_data:
  static_volume: